url: ""
name: Thinking.Minecraft
description: A blog about the game we all love!
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: "wp-content"
    values:
      image: true
